stages:
  - package
  - sign
  
package-win64-release:
  image: registry.swissqprint.com/sqp/devops/runner/msvc-2019:0.4-x86_64
  stage: package
  tags:
    - docker
    - windows
    - x86_64
  only:
    - tags
  script:
    - conan remove sqpQtIFW -f
    - conan create . installer/release -s build_type=Release
    - conan upload sqpQtIFW --all -r=inhouse -c

sign:
  needs: ["package-win64-release"]
  only:
    - tags
  variables:
    PKG_REFERENCE: sqpQtIFW/$CI_COMMIT_TAG@installer/release
  stage: sign
  trigger:
    project: sqp/dt/pysigntool
    strategy: depend
