variables:
  PROJECTNAME: qtifw
  Qt_DIR: C:\Qt\static\5.10.1
  Qt_Tools: C:\Qt\Tools\QtCreator\bin

stages:
  - package
  
package-win64-release:
  stage: package
  tags:
    - conan
    - msvc14
    - windows
    - x86_64
    - qt5.10-static
  only:
    - tags
  before_script:
    - set PATH=%Qt_DIR%\bin;%PATH% # qmake
    - set PATH=%Qt_Tools%\bin;%PATH% # jom
  script:
    - conan remove sqpQtIFW -f
    - conan create . sqp/release -s build_type=Release
    - conan upload sqpQtIFW --all -r=inhouse -c