variables:
  PROJECTNAME: qtifw
  Qt_DIR: C:\Qt\static\5.10.1

stages:
  - package
  
package-win64-release:
  stage: package
  tags:
    - conan
    - msvc14
    - windows
    - x86_64
    - qt5.10-static
  only:
    - tags
  before_script:
    - set PATH=%PATH%;%Qt_DIR%\bin
  script:
    - conan remove sqpQtIFW -f
    - conan create . sqp/release -s build_type=Release --update
    - conan upload sqpQtIFW --all -r=inhouse -c