#ifndef BUILD_INFO_H
#define BUILD_INFO_H
// Will be generated by conanfile.py
#define SQP_IFW_VERSION_STRING  "none"
#define SQP_GIT_BRANCH          "none"
#define SQP_GIT_AUTHOR          "none"
#define SQP_GIT_HASH            "none"
#endif // BUILD_INFO_H
